### ISSUE TITLE
Linux and zip package issue.

### ISSUE THREAD

**Issue by akeanti** [BLITZ-BOTS/CLI#1]
The package used to zip the plugin n the publishing process isn't compatible with linux :>
![ezgif-2-5a0dfd5573](https://github.com/user-attachments/assets/a391abdf-5585-46d1-9612-bbf6bcd75247)

**Comment by C-h-a-r** [comment]
Do you have zip installed? 

try checking the version:

```
zip -v
```

if not install it (debian based) with:

```
sudo apt install zip
```
